<?php

namespace AppBundle\Repository;

/**
 * Tabla_EntidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tabla_EntidadRepository extends \Doctrine\ORM\EntityRepository
{
}
